version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=todo_app
      - MYSQL_USER=upendartodo
      - MYSQL_PASSWORD=upendartodo123
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0



volumes:
  mysql_data:
